[package]
name = "kayo-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
diesel = { version = "2.0.4", features = ["sqlite"] }
dotenv = "0.15.0"
ics = "0.5.8"
tokio = { version = "1.28.0", features = ["full"] }
