name: KAY/O SECURITY ALERT

on:
  schedule:
    - cron: '0 0 * * 6'

permissions: read-all
  
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
  

