name: KAY/O SECURITY ALERT

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: cargo audit your Rust Dependencies
        uses: actions-rust-lang/audit@v1.1.6
    

