name: KAY/O SECURITY ALERT

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
  pull_request:
  # Run manually
  workflow_dispatch:

permissions: read-all
  
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
  

